### ISSUE TITLE
Examples / Demo page with code examples.

### ISSUE THREAD

**Issue by mstnorris** [posva/vue-mdl#1]
Do you have a demo page with code examples?

**Comment by alioygur** [comment]
+1

or documentation

**Comment by posva** [comment]
I am working on it! I understand how unusable the framework is at the moment. I have a doc branch where I am still building things up. Doc is my priority now. I won't add any more features until I have a doc :smile:

**Comment by posva** [comment]
Actually there are some examples inside the test/components folder if you want to start building things

**Comment by posva** [comment]
@mstnorris @alioygur I just noticed I wasn't watching my own repo which is strange... I wasn't getting any notifications

**Comment by mstnorris** [comment]
No worries. I look forward to seeing what you get up to. Do you have an ETA?

**Comment by posva** [comment]
Unfortunately providing an ETA is quite difficult but I will do my best to have at least some components documented and the doc online by the end of this week

**Comment by mstnorris** [comment]
That's ok, just knowing something is actively developed is great. I'll try and use it and give you some feedback.

Thanks.

**Comment by posva** [comment]
That would be great! Thanks for your support

**Comment by posva** [comment]
@mstnorris @alioygur The documentation workflow is ready. There is some doc available at http://posva.net/vue-mdl/

**Comment by acourtiol** [comment]
Wow~~ ! [Doge](http://i.imgur.com/P6xYV7s.jpg)

**Comment by posva** [comment]
@acourtiol haha, thanks :smile: 

@mstnorris, @alioygur The first version of the doc is ready so I am closing this issue. I'm however looking for feedback
