### ISSUE TITLE
Migrate from coffeescript to es6

### ISSUE THREAD

**Issue by dacodekid** [posva/vue-mdl#10]
As you may know this already, there is an old `github` joke about `coffeescript` that "a library author uses `coffeescript` to reduce `pull requests`".  Both `jade` & `coffeescript` might not be our `cup of tea` for many of us (I personally use `jade` but only on private repos).

Could you plz consider moving this repo to pure ES5/ES6 & HTML instead?

**Comment by posva** [comment]
This is something I've been considering for a while. I want to make sure this is worth the changement : people will issue more prs and contribute more. 

If I move I'll move to es6.  I don't know about html, jade is certainly better and it doesn't cost much

**Comment by posva** [comment]
Ok, so I created a tweet with a poll and a post on the Vuejs forum http://forum.vuejs.org/topic/2062/should-i-move-vue-mdl-to-es6-instead-of-coffee
https://twitter.com/posva/status/697041961329549312

**Comment by acourtiol** [comment]
@posva :smiley: 
https://github.com/decaffeinate/decaffeinate

**Comment by posva** [comment]
Thanks, I'm actually already using it to move the code to es6 😛

**Comment by smartpierre** [comment]
Yes ! Awesome !

**Comment by posva** [comment]
I'm almost done with this. The only thing left to migrate is the doc which should not take much time as there is not much code :smile:

**Comment by DualWield** [comment]
It's awesome!!

**Comment by smartpierre** [comment]
:+1:

**Comment by posva** [comment]
It should be good, I need to test a bit the new version (v0.4.0) to see if it still works :stuck_out_tongue: 
Any feedback is welcome :smile:
