### ISSUE TITLE
required field

### ISSUE THREAD

**Issue by kyoukhana** [posva/vue-mdl#101]
I couldn't get required working is there something I am missing? 

```
  <p><mdl-textfield floating-label="First Name:" :required="required" :value.sync="user.name" id="name" name="name"></mdl-textfield></p>
                                    <label class="mdl-textfield__error" v-if="error">{{error}}</label>
```

Also I coudln't get vee-validate working with any mdl-textfields.  It will work on normal input fields.

**Comment by posva** [comment]
I couldn't find anything missing.
You should post on the forums or SO to get some help
