### ISSUE TITLE
Binding rows of a textfield causes visual glitches

### ISSUE THREAD

**Issue by dsl101** [posva/vue-mdl#113]
This might be a question rather than a bug, but my naive method to make a text area which 'grows' with content was this:

    <mdl-textfield
      textarea
      :rows="editHeight"
      v-model="value"
      @keyup.native.enter="addItem"
      @input="checkSize"
      :label="textPrompt"
    ></mdl-textfield>
    ...
    checkSize () {
      this.editHeight = this.value.split("\n").length
    }

When I paste something with multiple lines into that, the MDL 'underline' highlight gets stuck at the bottom of the first text row, and the textarea grows underneath it. Is that just an MDL problem? Or is there a better way to make the textarea grow in vue-mdl?

**Comment by posva** [comment]
You can use something like autosize for that: http://www.jacklmoore.com/autosize/
Here's a way of doingn so with Vue: https://github.com/egoist/vue-autosize-textarea/issues/1#issuecomment-239754106
