### ISSUE TITLE
mdl select - options not selecting

### ISSUE THREAD

**Issue by devomacdee** [posva/vue-mdl#116]
In my project and in the docs, it does not register a click to select the option.

**Comment by posva** [comment]
Can you be more specific, please? Maybe you're using `@click` instead of `@click.native`

**Comment by devomacdee** [comment]
Sorry I actually got it working about 30 seconds ago. Still doesn't close when an option is selected though.

**Comment by devomacdee** [comment]
Sorry I actually got it working about 30 seconds ago. Still doesn't close when an option is selected though.

**Comment by posva** [comment]
That may be due to dynamic options. It currently doesn't support it :(
