### ISSUE TITLE
Check 'is-dirty' and Trigger 'change' events on appropriate components

### ISSUE THREAD

**Issue by dacodekid** [posva/vue-mdl#12]
There is a discussion thread [here](http://forum.vuejs.org/topic/2065/vue-vue-mdl-material-design-lite-change-event-approach).

I'm fairly new to `vue` & `mdl`, so not sure whether any other components other than `textfield` implements `is-dirty` checking, but would like to see `vue-mdl` check underlying model's value and trigger   /call `mdl`'s `change()` and `checkDirty` events.

**Comment by posva** [comment]
Thanks for this!
As I'm currently moving the repo to es6 I won't be able to work on it until I'm done with it and some other features that are have a higher priority but I'll address the issue in the future :smile:

**Comment by posva** [comment]
Hello! I finally got time to look into it. I'll keep you updated on this :smile:

**Comment by posva** [comment]
@dacodekid Adding a simple watch solves the issue. I have to write the tests yet so it may be done tomorrow
