### ISSUE TITLE
Better MDL installation guidelines

### ISSUE THREAD

**Issue by DualWield** [posva/vue-mdl#13]
I try to use it, but there is no mdl style.

can anyone tell me where to find the style assets?

**Comment by DualWield** [comment]
fine,I find it.http://www.getmdl.io/started/

**Comment by posva** [comment]
Glad you found. It is supposed to be on the Installation part on the doc http://posva.net/vue-mdl/#installation but it's not very clear.
I'm reopening this so I have a reminder about adding some code samples
