### ISSUE TITLE
support mdl-layout

### ISSUE THREAD

**Issue by andyforever** [posva/vue-mdl#16]
Hope early support mdl-layout. I think it's a base element to build an APP or Website. 

Thanks for the great job.

**Comment by posva** [comment]
Hi, thanks for submitting the request. I'll address it as soon as I can

**Comment by andyforever** [comment]
Hi,Posva.
I have a proposal for the project,but I do not know if it would work.It's about the register method.
I think it's a little complex to register every component before I use it. Would you consider creating a Vue directive for each component for the register? Then we can just add a attribute to register it.
The inspiration comes from an article from the [Vue forum](http://forum.vuejs.org/topic/893/vue-js-foundation-6/5).

**Comment by posva** [comment]
Hi, I took a look at the forum post. The directives examples is indeed interesting, however vue-mdl aims to create reusable components that offers more than just a call to the `componentHandler.upgradeElements(this.el)` method

Concerning the current way of registering components and directives, I'm going to remove the existing methods and make vue-mdl a plugin that also expose each directive and component. This way you either register everything with `Vue.use(vueMdl)` and also pick only the components you want to register with `import MdlButton from 'vue-mdl'`

Hope this helps you :smile:

**Comment by andyforever** [comment]
That's helpful.
Thanks.

**Comment by IvoPereira** [comment]
+1 on this.

It is a basic need for building a web app.

**Comment by posva** [comment]
I know, I'm sorry I couldn't work on this enough, I wish I had more time to do it but I can only work on my spare time 😭 
mdl Layout is a bit more complicating than I expected back when I started working on it because there're a lot of different cases and I need to make it easy to handle the layout. I shall give it another try next week

**Comment by NathHorrigan** [comment]
Any updates on this, great library btw 👍

**Comment by posva** [comment]
Thanks! I added the tabs a couple of days ago (that's what I ended up looking at). I expect being able to work on this during the next week. If only I could do this during my daily job 😩
The project is active but I wish I had more time for it...

**Comment by atjonathan** [comment]
@posva, any update on this?

**Comment by posva** [comment]
@atjonathan Unfortunately I couldn't yet find the time for this. I've being focusing on vue-router 2 and supporting Vue 2 for vue-mdl. I think the later is more important atm because you can still use mdl layouts and apply the directive `v-mdl` to them

**Comment by laurentpayot** [comment]
@posva are you aware of this ? (mdl2 + vue2) : https://github.com/google/material-design-lite/tree/master/examples/vue

**Comment by posva** [comment]
@laurentpayot I wasn't aware of the examples but I was aware of mdl 2 which is still very unstable.
Thanks for sharing! I've checked a bit. As soon as mdl 2 gets mature I'll get to implement them. It should even be faster to implement. I may restart the project from scratch actually

**Comment by laurentpayot** [comment]
@posva By the way it is not obvious how we shoud use `v-mdl` with mdl layouts.
Suppose I have the following structure:

```html
<!-- Layout.vue -->
<div class="mdl-layout mdl-js-layout">
  <navbar></navbar>
  <sidebar></sidebar>
  <main class="mdl-layout__content">
    <router-view></router-view>
  </main>
</div>
```
```html
<!-- Navbar.vue -->
<header class="mdl-layout__header">
  <div class="mdl-layout-icon"></div>
  <div class="mdl-layout__header-row">
    <span class="mdl-layout__title">Simple Layout</span>
    <div class="mdl-layout-spacer"></div>
    <nav class="mdl-navigation">
      <a class="mdl-navigation__link" href="#">Nav link 1</a>
      <a class="mdl-navigation__link" href="#">Nav link 2</a>
      <a class="mdl-navigation__link" href="#">Nav link 3</a>
    </nav>
  </div>
</header>
```

```html
<!-- Sidebar.vue -->
<div class="mdl-layout__drawer">
  <span class="mdl-layout__title">Simple Layout</span>
  <nav class="mdl-navigation">
    <a class="mdl-navigation__link" href="#">Nav link 1</a>
    <a class="mdl-navigation__link" href="#">Nav link 2</a>
    <a class="mdl-navigation__link" href="#">Nav link 3</a>
  </nav>
</div>
```
Where exactly should I put `v-mdl`? I'm getting infinite loops when I try…

**Comment by posva** [comment]
My bad! `v-mdl` is not the way for that. You should just use plain mdl `componentHandler.upgradeElement(this.$el)` in Layout.vue should work

**Comment by laurentpayot** [comment]
Do you mean in the `ready` hook like the following?
```javascript
  ready () {
    componentHandler.upgradeElement(this.$el)
  }
```
And if yes, not in Navbar.vue nor Sidebar.vue even if I will put some components (vue-mdl + my own ones) inside them?

**Comment by posva** [comment]
Yes, You can also pass a second parameter to that method specifying the component, so in this case `MdlLayout` I believe, but you shouldn't need that 😄

**Comment by laurentpayot** [comment]
Thanks @posva, reading [this](https://github.com/google/material-design-lite/issues/871) also helped me clarify things.

 PS: October is going to be a long month 😄

**Comment by dsl101** [comment]
I'm using Vue mdl-layout, but with tabs instead of nav elements. I was going to ask elsewhere about using mdl-tabs in this scenario, but it seemed appropriate here, as supporting tabs would mean doing something in mdl-layout too I suspect. Currently, plain MDL separates out the tab _links_ from the tab _content_, so that the links can be inside the header element, but the content in the main page area. I can't see how to do that with v-mdl. Are there plans to extend v-mdl tabs so that can be used with the layout element?

**Comment by posva** [comment]
@dsl101 I suggest you to just use the tabs as they're used with the original mdl-layout.

**Comment by dsl101** [comment]
Yes, I think that's the only option for the moment. But it looks like [tabs are changing in MDL](https://github.com/google/material-design-lite/issues/4481) anyway, so hopefully v-mdl will support the new version at some point in the future.

**Comment by posva** [comment]
@dsl101 That's the v2 of mdl, vue-mdl will have to be rewritten anyways 😉

**Comment by dsl101** [comment]
Of course. I'm eagerly awaiting V2 of MDL anyway, as the current tab implementation is tricky to control from code rather than static data. I'm assuming there'll be much wider implications for v-mdl than just tabs though :).

**Comment by posva** [comment]
Closing as done in #90 
It's still missing tabs though. I may add that in the future. Scoped slots makes the api much better
