### ISSUE TITLE
textfiled on keyup.enter

### ISSUE THREAD

**Issue by vicmars5** [posva/vue-mdl#162]
Hello, I am not sure if is posibble to pass a method to execute when enter key is pressed?, or do i need to modify the textfield component to add the functionallity?.

**Comment by dsl101** [comment]
You can bind a method you provide to the `keyup` event. For example, use this for the Enter key:

    <mdl-textfield @keyup.native.enter="onEnter"></mdl-textfield>
    .
    .
    .
    methods: {
        onEnter () {
            .
            .
            .

The `.native` modifier is needed, and if you want to catch _every_ key, just leave out the `.enter` modifier in the event binding.
