### ISSUE TITLE
Component naming

### ISSUE THREAD

**Issue by BrainMaestro** [posva/vue-mdl#23]
I understand the idea behind prefixing your components with `mdl` to avoid name clashes with regular html elements. But I feel like it'll be cleaner without those. Check out [Material UI](https://github.com/callemall/material-ui) a similar project built in react.

**Comment by posva** [comment]
Hello @BrainMaestro 
As you said, the reason why components are prefixed with `mdl` is to make a difference between custom components and native tags like `a` or `img`, I'm not sure if it's on the HTML5 spec or not, however it does make sense to make the difference. Here's an article about it: http://www.html5rocks.com/en/tutorials/webcomponents/customelements/

You can already register them without a prefix:

```js
import { MdlCheckbox as Checkbox } from 'vue-mdl'

new Vue({
  components: {
    Checkbox
  }
})
```

IMO it is possible to add an option when registering the plugin to customise the prefix or event delete it:

```js
Vue.use(VueMdl, { prefix: ('' | null | undefined) }) 
// --> <checkbox></checkbox>
Vue.use(VueMdl, { prefix: 'foo' }) 
// --> <foo-checkbox></foo-checkbox>
```

In that case, PR are welcome :smile:

**Comment by BrainMaestro** [comment]
Oh that seems like a really cool idea! I'm new to vue but i'll try.

**Comment by posva** [comment]
Some tips: the code you have to update is here; https://github.com/posva/vue-mdl/blob/develop/src/vue-mdl.js#L50-L57
You have to add an optional `options` parameter to the install function (http://vuejs.org/api/#Vue-use)

**Comment by BrainMaestro** [comment]
After giving it more thought, the change doesn't seem worth it. 

Separate question. Do you plan on expanding your components past those in Material Design Lite which is missing quite a few of the components. Or would you rather not do the styling involved.

Great project btw :+1:

**Comment by posva** [comment]
Ok, no problem  :smile: closing the issue then
Yes, I do. I also accepts other contributions sometimes. At th moment there is the select and dialog component. They're both unde the custom components category

Thanks!
