### ISSUE TITLE
"for" prop on tooltip

### ISSUE THREAD

**Issue by smartpierre** [posva/vue-mdl#26]
Hi !

first of all, thank you for your work, it's amazing !

I am trying to use the tooltip component in a loop and I can't manage to have a dynamic "for" property. See my code here : 

![screenshot from 2016-04-14 16-01-48](https://cloud.githubusercontent.com/assets/8858750/14530682/529c168e-025a-11e6-9a6a-7ecad2489a8c.png)

That gives : 

![screenshot from 2016-04-14 16-00-31](https://cloud.githubusercontent.com/assets/8858750/14530688/5b6aafaa-025a-11e6-8a7b-d702828b23c7.png)

It's a simple usage but I don't know how I can make it work.

Thanks !

**Comment by posva** [comment]
Hello,

It's not that amazing, I'm still missing several components :sweat_smile:
But I really appreciate your support, so Thank you :smile: 

As a good practice you should never use `{{ }}` inside attributes. It doesn't work in props (I think)
Does it work using: `:for ="'profile' + profile.id"` ?

**Comment by smartpierre** [comment]
Oh god I completely forgot to put the ':' before 'for'
It works perfectly now, thank you ! I hope to see you at the next Meetup in Paris :)

**Comment by posva** [comment]
Good to know. See you next time at Algolia :wink:
