### ISSUE TITLE
Doc - Memory Leak

### ISSUE THREAD

**Issue by vbrajon** [posva/vue-mdl#27]
Hey posva,

Great job for vue-mdl !

I appear to have a memory leak on the documentation website.

I am on OSX / Chrome49. Do you need more info ?

PS: I will try to help you release 1.0, this project seems fun ;)

**Comment by posva** [comment]
Hey, thanks @vbrajon 
I'll give it a look. What were you doing to create the leak?

It makes me happy you want to contribute. Send me an email so can find a better way to communicate 😉

**Comment by posva** [comment]
@vbrajon I'm not sure it's a memory leak but it's definitely using too much CPU. I can reproduce it now by going to http://posva.net/vue-mdl or even by serving locally with `npm run dev:doc`

**Comment by posva** [comment]
Yeah, basically there's too much stuff on a single page. Using vue-router or a simple routing strategy would fix the problem

**Comment by posva** [comment]
I think everything is fine now that vue-router is used
