### ISSUE TITLE
About toggle and boolean

### ISSUE THREAD

**Issue by smartpierre** [posva/vue-mdl#28]
Hi !

I am using the toggle component in my project. 

However, the variable I am using for this component comes from an API with a value of **0** or **1** and the toggle component only recognize **true** or **false**. Is it my job to handle that or maybe we can improve the toggle component to be a little bit smarter ?

```
<mdl-switch :checked.sync="something" class="mdl-js-ripple-effect">
 </mdl-switch>

something = 0

[Vue warn]: Invalid prop: custom validator check failed for checked="something"
....
```

Thanks !

**Comment by posva** [comment]
Hi,
As long as the v-model works with it, the component should follow.
If you want you can change the mixin https://github.com/posva/vue-mdl/blob/develop/src%2Fmixins%2Ftoggle.js and add a test for it in any of the toggles components
Otherwise I'll take a look asap and keep you informed

**Comment by smartpierre** [comment]
Wow ! Thank you ! I just came back from holiday and completely forgot to do it beforehand.

:+1:
