### ISSUE TITLE
Not giving a prop a value should consider it as true in HTML

### ISSUE THREAD

**Issue by RiseupDev** [posva/vue-mdl#3]
I kept trying to add the prop 'raised' and 'colored' to an mdl-button but with no luck:

```
<mdl-button raised colored v-mdl-ripple-effect>
<i class="material-icons">content_paste</i>
</mdl-button>
```

all i get is a basic button with ripple effect

**Comment by posva** [comment]
Can you give me a repro, pleas. The example on the doc works just fine (the playground

**Comment by RiseupDev** [comment]
sure i'll make a repo

**Comment by RiseupDev** [comment]
you can view the code here: https://github.com/RiseupDev/mdl-test

**Comment by posva** [comment]
I see, you're missing the material design lib. This is something that should be clarified in the future with an example boilerplate. I added a comment about this in the doc but it's not enough. I'll update the readme as well.

Check http://www.getmdl.io/started/index.html

**Comment by RiseupDev** [comment]
i'm not missing them, thy're in the index.html file

**Comment by posva** [comment]
mmh, I somehow missed that with the search. I'll get a closer look

**Comment by posva** [comment]
Turns out it has to be `raised=raised`

I got tricked by jade. I'll try to fix it, if I can't i'll update the doc. Thanks!

**Comment by RiseupDev** [comment]
ok thanks :+1:

**Comment by posva** [comment]
You can now update to the v0.3 and write `raised` without passing a value

**Comment by RiseupDev** [comment]
nice :+1:
