### ISSUE TITLE
v0.7.4 requires Vue >= 1.0.21

### ISSUE THREAD

**Issue by Fedia** [posva/vue-mdl#30]
Thank you for a great lib, Eduardo!
For those of us who don't use NPM, it should probably be noted that vue-mdl v0.7.4 requires Vue >= 1.0.21.

```javascript
props: {
    checked: {
      type: [Array, Boolean, Number], // Vue < 1.0.21 throws an exception
      required: true,
      twoWay: true
    }
}
```

**Comment by posva** [comment]
Hello @Fedia 
Thanks! I think a simple modification to the readme is enough. Specifically the line:

> vue-mdl tries to use the latest versions of material design lite and vue.

may be replaced by 

> vue-mdl relies on the **last version of vue and material design lite**. Make sure to have your modules up to date 😉 

What do you think? What were you expecting? Was it a note on the release notes?

**Comment by Fedia** [comment]
@posva 
Yeah, this **"make sure"** line would be a time saver for those non-reading ADHD folks like me. Thanks!
