### ISSUE TITLE
Gulp + Browserify error

### ISSUE THREAD

**Issue by wergimity** [posva/vue-mdl#31]
Hi, when I try to import vue-mdl module I get this error:
```
Cannot find module '!!./../node_modules/css-loader/index.js?sourceMap!./../node_modules/vue-loader/lib/style-rewriter.js!./../node_modules/vue-loader/lib/selector.js?type=style&index=0!./select.vue' 
```

My `gulpfile.js`
```
var gulp = require('gulp'),
    browserify = require('browserify'),
    source = require('vinyl-source-stream'),
    buffer = require('vinyl-buffer'),
    uglify = require('gulp-uglify'),
    sass = require('gulp-sass'),
    livereload = require('gulp-livereload'),
    concat = require('gulp-concat'),
    babel = require('gulp-babel');

gulp.task('browserify', function() {
    browserify('src/app.js')
        .transform('babelify', {presets: ['es2015', 'react']})
        // .transform('envify')
        .transform('vueify')
        .bundle()
        .on('error', function(e) {
            console.error(e.message);
        })
        .pipe(source('app.js'))
        .pipe(buffer())
        .pipe(gulp.dest('www/js'))
        .pipe(livereload())
});
```

**Comment by posva** [comment]
You seem to be missing the css loader https://github.com/vuejs/vueify#usage
Also you won't need that if you include the compiled version (that's the default behaviour when doing `import VueMdl form 'vue-mdl'`)

**Comment by wergimity** [comment]
Thanks. I used `import VueMdl from 'vue-mdl/dist/vue-mdl.min';` and now everything works perfectly!

**Comment by posva** [comment]
That's weird, I must have messed up the package in some commit. Thanks for reporting it, I will take a deeper look

**Comment by Mdpproduction** [comment]
Hi all,
if i import the vue-mdl like `import VueMdl from 'vue-mdl/dist/vue-mdl.min'`, during compiling with browserify it's all ok. But when i try to use some component i get this error:

`Uncaught ReferenceError: componentHandler is not defined`

I'm using laravel elixir, and i'm usign vue 1.0.20, could be the problem ?

**Comment by posva** [comment]
@Mdpproduction I updated the readme. You need to install MDL

**Comment by Mdpproduction** [comment]
Thanks, i've already installed MDL. But i don't know why, the effetc on textfield, ripple ecc ecc, doesn't works yet. But thanks for the update!!

**Comment by posva** [comment]
You need to include both, js and css from MDL. You're missing one of them for sure or you're including them in the wrong order. I'm sure you'll find out the issue in very little time 😉

**Comment by Mdpproduction** [comment]
Works :dancers: thanks again man!!

**Comment by clemf** [comment]
@Mdpproduction How did you end up solving this issue?

**Comment by Mdpproduction** [comment]
Yep. You need to import mdl.min from dist source.
