### ISSUE TITLE
Vue-validator works with mdl textfield ?

### ISSUE THREAD

**Issue by Mdpproduction** [posva/vue-mdl#33]
Hi,
this is a question more than an issue. I'd like to know, if it's possible to make work togheter vue-validator and mdl-textfield for validation. I'll tried to add the rules, but doesn't work. Any suggestions ?

**Comment by posva** [comment]
You can use the slots to define your own inputs
https://github.com/posva/vue-mdl/blob/develop/src%2Ftextfield.vue
It may be worth to transfer the directive v-validate to the input or the textarea
Also I think there should be two components: input and textarea. I'd make dev easier

**Comment by posva** [comment]
@Mdpproduction After giving it a try, the best way to go is to customise the input with a slot. I'll think about it and try to find a better way to support vue-validator

**Comment by Mdpproduction** [comment]
Thanks man, i'll waiting for updates!!
