### ISSUE TITLE
For MdlDialog, the MdlButton action buttons must be defined before use

### ISSUE THREAD

**Issue by danneker** [posva/vue-mdl#34]
I created the following dialog:
```jade
mdl-dialog(v-bind:title="title" display-on="actionDialog")
  p {{ text }}
  template(slot="actions")
    mdl-button(v-for="actionName in actionNames" primary raised) {{ actionName }}
```
```javascript
export default {
  data: {
    title: 'This is the title',
    text: 'This is the text',
    actionNames: ['Action1', 'Action2', 'Action3'],
    actions: [this.callAction1, this.callAction2, this.callAction3],
  },
  methods: {
    openDialog () {
      this.$broadcast('actionDialog', ...this.actions)
    },
    callAction1 () {
      console.log('action1')
    },
    callAction2 () {
      console.log('action2')
    },
    callAction3 () {
      console.log('action3')
    }
  }
}
```

When calling openDialog, the dialog is displayed but the actions are not added to the buttons. In fact, when I click on the button nothing happens. If I close the dialog and reopen it, the buttons work as expected.

This code however seems to work the first time:
```jade
mdl-dialog(v-bind:title="title" display-on="actionDialog")
  p {{ text }}
  template(slot="actions")
    mdl-button(primary raised) {{ actionName[0] }}
    mdl-button(primary raised) {{ actionName[1] }}
    mdl-button(primary raised) {{ actionName[2] }}
```
Maybe an issue with the adding of the actions to the buttons that takes place before/after the v-for?

**Comment by posva** [comment]
That's normal because `this.callAction1` in undefined in that scope 😛 
I'm thinking about removing the event and use a direct method instead. It's weird that it works at a second try though...

**Comment by danneker** [comment]
When I pass the functions they seem to be called even though though they come from another scope. I'm no expert on javascript but this.callAction1 does not seem to be undefined (at least not the second time or in the second example).

Using direct methods might be better.

**Comment by posva** [comment]
Can't you do `this.$broadcast('actionDialog', [this.action1, this.action2, this.action3])` ?

**Comment by danneker** [comment]
I thought the same thing but when I tried I had the same outcome. It really seams to be something with the v-for. Like the button is not yet created and so the action is not correctly added to it.

**Comment by posva** [comment]
You're right! The problem is with the v-for. I'll remove the automatic action insertion. People should handle actions themselves when overriding the template. What do you think?

Thanks for reporting this! 😄

**Comment by danneker** [comment]
I agree, people should handle the actions themselves. Like that the code is easier to understand. It would be nice, however, if you update the example for this case so that people can see how the override works.

You are welcome for the report! Glad I can help, even if just a little. ;)

**Comment by posva** [comment]
Sure, I'll do that 👍
