### ISSUE TITLE
support mdl-table

### ISSUE THREAD

**Issue by keepwn** [posva/vue-mdl#35]
Hi!
I created a table and used code like these, just copy from [mdl-table](https://getmdl.io/components/index.html#tables-section)

*native mdl-table code*
```html
<table class="mdl-data-table mdl-js-data-table mdl-data-table--selectable mdl-shadow--2dp">
  <thead>
    <tr>
      <th class="mdl-data-table__cell--non-numeric">Material</th>
      <th>Quantity</th>
      <th>Unit price</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td class="mdl-data-table__cell--non-numeric">Acrylic (Transparent)</td>
      <td>25</td>
      <td>$2.90</td>
    </tr>
    <tr>
      <td class="mdl-data-table__cell--non-numeric">Plywood (Birch)</td>
      <td>50</td>
      <td>$1.25</td>
    </tr>
    <tr>
      <td class="mdl-data-table__cell--non-numeric">Laminate (Gold on Blue)</td>
      <td>10</td>
      <td>$2.35</td>
    </tr>
  </tbody>
</table>
```

The code created some checkboxes in first column, but i could not get checkboxes' status in vue.
So, i have to write some code to create checkboxes and get these status instead of  using `mdl-data-table--selectable` in mdl-table.
Have a better way？Or will support mdl-table?

**Comment by posva** [comment]
IMO you should create the checkboxes yourself, remove the `mdl-data-table--selectable` and bind them like usual with `v-model`. I do plan in supporting `mdl-data-table` but there may be some issues until Vue 2 because of the native `tr`, `th` and `td` elements

**Comment by keepwn** [comment]
I tried to create the checkboxes myself, but i seem to have a little problem.
When mutil-select `input checkbox`, `checkboxes` will be a array like `[tr0,tr1]`, but `mdl-checkbox` behavior different than expected.

```html
<div class="container">
    <table id="banding-table" class="mdl-data-table mdl-js-data-table mdl-shadow--2dp">
    <thead>
        <th>
        <mdl-checkbox v-mdl-ripple-effect :checked.sync='checked'></mdl-checkbox>
        </th>
        <th>Name</th>
    </thead>
    <tbody>
        <tr v-for="service in services" id="tr{{ $index }}">
        <td>
            <mdl-checkbox v-mdl-ripple-effect :vaule="$index" :checked.sync='checkboxes'></mdl-checkbox>
            <input type="checkbox" value="tr{{ $index }}" v-model="checkboxes">
        </td>
        <td>{{ service.name }}</td>
        </tr>
    </tbody>
    </table>
    <br>
    <span>Checked names: {{ checkboxes | json }}</span>
</div>



export default {
    data () {
        return {
            checked: false,
            checkboxes: []
        }
    }
}
```
Am i ignore something?

**Comment by keepwn** [comment]
e....I made a stupid mistake(`vaule` => `value`).:flushed:
It works fine now, thx.

**Comment by posva** [comment]
no worries 😄 
Remember you can use a computed value with a setter for the header checkbox
