### ISSUE TITLE
The missing card component

### ISSUE THREAD

**Issue by geeeeeeeeek** [posva/vue-mdl#4]
Card is an essential component in Material Design. Should this be implemented soon?

**Comment by posva** [comment]
Yes, I'm getting to it very soon :smile:

**Comment by posva** [comment]
However cards doesn't need any component to be used. It'll certainly add some sugar for the component but that's pretty much everything

**Comment by geeeeeeeeek** [comment]
@posva great!

**Comment by posva** [comment]
I'm sorry this took so much, I'm not even done with the feature yet :sweat_smile: 
I'm soon releasing a version with an usable card. I'm planning on adding more features and provide better doc on the near future now that I got more free time
