### ISSUE TITLE
Mdl-Select click issues inside Mdl-Dialog

### ISSUE THREAD

**Issue by phillycheeze** [posva/vue-mdl#40]
When a select field is inside a dialog box, clicking an element in the select doesn't close the select box. 

It looks like some issue inside the dialog component preventing the click from propagating through.

**Comment by posva** [comment]
Thanks for reporting it. I'll take a look asap 😄

**Comment by posva** [comment]
It seems to work on develop. Can you checkout the example in the develop branch please? You can run the test examples with `npm run dev:integration`, then go to `localhost:8080` and press the next button until you get to the  Dialogs page

**Comment by phillycheeze** [comment]
Thanks for the comment!

I did try that and it worked as you said. I have figured out the actual problem.

When the `:options` attribute points to a Vuex getter, it causes the select box not to close when an item is selected. I am not sure why this is happening, so I might try to look into it. 

Do you happen to have any ideas?

**Comment by posva** [comment]
Vuex getters should work as any other variable 😕 
I don't have any ideas. MDL bind events listeners when the menu is shown. You may look there.
Closing this since it's not a vue-mdl issue
