### ISSUE TITLE
Selects

### ISSUE THREAD

**Issue by enriquezafra** [posva/vue-mdl#43]
Is correct for remove the "is-focused" class after making the selection add this?

```
setName () {
  ...
  this.$els.textfield.classList.remove("is-focused")
}
```

**Comment by posva** [comment]
It took me some time to understand that 😅 
Yes, we should remove it. The best way is to call the MDL method for it: `this.$els.textfield.MaterialTextfield.boundBlurHandler()`

**Comment by enriquezafra** [comment]
Ok, Thanks for the great job.

**Comment by posva** [comment]
If you want to create the PR and need some help, I'm willing to do so 😄
