### ISSUE TITLE
how to reset mdl-select

### ISSUE THREAD

**Issue by xinz** [posva/vue-mdl#44]
Hi,

`<mdl-select label="Country" id="contry-select" :value.sync="country" :options="countriesArray"></mdl-select>`

Once select one option of this component, how can I reset this component via the defined vm's methods, just like this component initialization? I try updating the `vm.country` as null or "", but it doesn't work as expected.

Appreciate your help!

**Comment by posva** [comment]
Thanks! You found a bug. Should be fixed in next release
