### ISSUE TITLE
mdl-checkbox Safari keyboard focus

### ISSUE THREAD

**Issue by patriciussanctus** [posva/vue-mdl#45]
hi!
I try press key "Tab" on keyboard from safari 9.1 and getn't effect focus into checkboxes.

**Comment by posva** [comment]
Indeed, although it doesn't work on the MDL site: https://getmdl.io/components/index.html#toggles-section

I'll suggest opening an issue there.

PS: First time I ever tried that on Safari. Didn't know you have to activate it through preferences. It does feel weird 😕
