### ISSUE TITLE
Mdl-Select click issue

### ISSUE THREAD

**Issue by Maxlone** [posva/vue-mdl#46]
I found out that if you push new data to the array that `:options` pointed to,clicking an element in the select doesn't close the select box. Is there any way to solve this issue?

**Comment by posva** [comment]
Sorry for not answering. I completely forgot 😓 
This is a real issue because at the moment the mdl menu is created only once and therefore any menu item added afterwards doesn't work properly

**Comment by jamiedumont** [comment]
I thought I'd add my `++` for reference. I'm too having this issue, and can't find a way to resolve it.

**Comment by posva** [comment]
I think I should rethink the way mdl-menu handles options. I may end up doing something like mdl-tabs but this one is more complicated

**Comment by kyoukhana** [comment]
I encountered this problem as well.  I think if we load the lists dynamically there should be a option to re-bind the click on the options.  It seems like its a binding issue on click.   Also if you are pulling a list from the database the column name in the database has to be value.

**Comment by devomacdee** [comment]
Has this been resolved? I'm having this same issue still.

**Comment by posva** [comment]
ATM you need to manually handle it for dynamicaly added options: https://jsfiddle.net/posva/rc1u7ouc/
Basically you need to call a handler on click:

```js
   handleClick (e) {
    	this.$refs.menu.$el.MaterialMenu.handleItemClick_(e)
    }
```

**Comment by sofanisba** [comment]
```
<mdl-select label="Category"
                  id="category"
                  v-model="category"
                  :value="category"
                  :options="categories">
</mdl-select>
```
The example given above binds the handleClick event to a child component of the menu. In this case the `:options` list items would be the thing with an event binding, but those are only referenced in the mdl-select tag.  Any suggestions as to how one would add that click handler to a stock mdl-select component's child elements?

**Comment by posva** [comment]
I think the select component could probably be updated to handle the click itself: https://github.com/posva/vue-mdl/blob/develop/src/select.vue#L36

the select is a hack after all

**Comment by sofanisba** [comment]
Yeah, my last-ditch effort is to fork it and change the `<li>` event handler, but I figured I'd see if there was some clever on the fly fix. :+1:

**Comment by posva** [comment]
Make sure to share it as a PR if you add it 🙂

**Comment by AliShaikh94** [comment]
Was there a fix for this? 
Even on the doc website the select component is broken :(

**Comment by posva** [comment]
It doesn't work because I forgot to update the docs at https://github.com/posva/vue-mdl/blob/develop/doc/src/views/Selects.vue for Vue 2 but there's a working example at https://github.com/posva/vue-mdl/blob/develop/test/components/Select.vue
I'm open to a PR for that

**Comment by AliShaikh94** [comment]
Yeah I saw that and got it working from there. 
I've fixed it locally in the docs, did you want me to create a new branch and then send a PR from there?

**Comment by posva** [comment]
Yes, that would be great ☺️
