### ISSUE TITLE
mdl-select async dynamically update options

### ISSUE THREAD

**Issue by xinz** [posva/vue-mdl#47]
Hi,

In the vue instance's lifecycle hooks (I try created / ready / beforeCompile), I want to dynamically load the `options` data from the `promise` object, but I find that once using the async http request/response, the options can be displayed, but after select one item, the populated options menu won't hide. Do you have any suggestions to resolve this issue?

Thanks.

**Comment by posva** [comment]
yeah, there's a bug about it. Options are only considered at creation so they cannot be later modified.
Duplicated of #46

**Comment by xinz** [comment]
Thanks for your confirmation.
