### ISSUE TITLE
Install vue-mdl from npm return v0.75

### ISSUE THREAD

**Issue by Mdpproduction** [posva/vue-mdl#48]
Good evening,
i re-installed vue-mdl for another project from npm. But when the installation is finished, i see that the version is the 0.75 and not the latest. How can i fix that ?

**Comment by posva** [comment]
I tested installing on a clean projet and it installs the last version. There's never been a 0.75 version. Something must be wrong with your env 😕

**Comment by Mdpproduction** [comment]
My bad. Sorry 😃
