### ISSUE TITLE
Selects

### ISSUE THREAD

**Issue by martinlindhe** [posva/vue-mdl#5]
While I realize mdl itself doent yet provide a select component to forms, the need
have arisen for me.

I hope to one day see support for this in vue-mdl :-)

Upstream: https://github.com/google/material-design-lite/issues/854

The following vue component can be used in the meantime;
https://gist.github.com/martinlindhe/1693a2652bf2a609ee37

**Comment by posva** [comment]
Cool! Thanks for sharing that. I'll give it a look as soon as I'm done with cards :smile:

**Comment by randrianov** [comment]
Look at getmdl-select - that's the thing you really need! It provides a fast way to make select input with native Material design lite menu style.
https://github.com/CreativeIT/getmdl-select

[example page](http://creativeit.github.io/getmdl-select/)

hope it'll help you

![select](https://cloud.githubusercontent.com/assets/1220390/13027413/70a5a8d6-d260-11e5-8cd1-9a91aeb688b6.gif)

**Comment by martinlindhe** [comment]
@randrianov if you look at the gist in first post, you will see that it is a vue component based on getmdl

**Comment by posva** [comment]
@randrianov Thanks, I already knew it but I appreciate your concern :smile:
