### ISSUE TITLE
mdl-select shows the value rather than name when selected item changed

### ISSUE THREAD

**Issue by hyiso** [posva/vue-mdl#50]
When I change the item selected, `mdl-select` shows the item.value rather than item.name.
 I've created a [demo on jsfiddle](https://jsfiddle.net/doezwsmu/)

It seems to be the problem with code in `src/select.vue` at line 52:
```
if (this.name === oldName) this.name = this.value
```
This code will always be triggered because it happens after value changed.

**Comment by posva** [comment]
Thanks for the detailed report!
I'll give it a look and solve it this evening
