### ISSUE TITLE
tabs of vue-mdl is not working

### ISSUE THREAD

**Issue by ShadowWood** [posva/vue-mdl#53]
Hello, there is a problem in my project when I use tabs of vue-mdl.

At first, I install vue-mdl in my application by this

```
import Vue from 'vue'
import VueMdl from 'vue-mdl'
import VueRouter from 'vue-router'
import Router from './router-config'
import App from './App'

 
Vue.use(VueMdl)
Vue.use(VueRouter)
 
var app = Vue.extend(App)
 
var router = new VueRouter({
   'linkActiveClass': 'active'
})

Router(router)


router.start(app,  '#app')`
```

And then I use mdl-tabs in my components, the error happening:

```
Unknown custom element: <mdl-tabs> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
Unknown custom element: <mdl-tab> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
```

I think that I have registered by Vue.use(VueMdl), because other components like mdl-card or mdl-button can work in my components.

**Comment by posva** [comment]
Are you using the last version (0.9.1)?

**Comment by ShadowWood** [comment]
No, I use version (0.8.5). Is it fixed in the last version (0.9.1)?

**Comment by ShadowWood** [comment]
I has already updated it, and it works. Thank you!

**Comment by posva** [comment]
Tabs were introduced in 0.9.1 😛
