### ISSUE TITLE
Setting a blank string on mdl-card actions attribute causes TypeError

### ISSUE THREAD

**Issue by agc93** [posva/vue-mdl#54]
I'm not sure if this is really a problem with vue-mdl, but it certainly seems like it might be.

When I define an mdl-card as follows:
```html
<mdl-card :title="title" :supporting-text="text" :actions="showLinks ? 'actions' : ''">
	<div slot="actions" v-if="showLinks">
		<!-- content here -->
	</div>
</mdl-card>
```

where `showLinks` is a computed boolean on my VM, I get a console error:

```
Uncaught TypeError: Cannot read property 'attributes' of undefined (vue.common.js?e881:3337)
```

Removing the binding for actions (i.e. the `:actions="showLinks ? 'actions' : ''"` everything starts working again. Do you have any idea what could cause this? Is there any more info I can provide?

Thanks again for an awesome library!

**Comment by agc93** [comment]
The stack trace when that error is thrown is:

```
TypeError: Cannot read property 'attributes' of undefined
    at eval (eval at <anonymous> (http://localhost:8080/dist/build.js:1551:2), <anonymous>:2317:17)
    at Array.forEach (native)
    at MdlCard.compiled (eval at <anonymous> (http://localhost:8080/dist/build.js:1551:2), <anonymous>:2314:12)
    at MdlCard.Vue._callHook (eval at <anonymous> (http://localhost:8080/dist/build.js:1539:2), <anonymous>:8235:21)
    at MdlCard.Vue._compile (eval at <anonymous> (http://localhost:8080/dist/build.js:1539:2), <anonymous>:8628:10)
    at MdlCard.Vue.$mount (eval at <anonymous> (http://localhost:8080/dist/build.js:1539:2), <anonymous>:9446:10)
    at MdlCard.Vue._init (eval at <anonymous> (http://localhost:8080/dist/build.js:1539:2), <anonymous>:2468:12)
    at MdlCard.Vue._init (eval at <anonymous> (http://localhost:8080/dist/build.js:3556:2), <anonymous>:1756:12)
    at new MdlCard (eval at createClass (eval at <anonymous> (http://localhost:8080/dist/build.js:1539:2)), <anonymous>:2:42)
    at Directive.build (eval at <anonymous> (http://localhost:8080/dist/build.js:1539:2), <anonymous>:5837:19)
```

**Comment by posva** [comment]
That's because you don't need the `v-if` in the slot. Vue-mdl does it for you. I better add that to the documentation

**Comment by agc93** [comment]
I took that v-if out of the slot, and even tried removing that whole `div` and same problem. The moment I add `:actions="showLinks ? 'actions' : ''"` to the containing `mdl-card` it all stops working.

**Comment by posva** [comment]
I cannot reproduce your issue copying the exact same template provided. Can you please create a jsfiddle with a reproduction?

**Comment by posva** [comment]
@agc93 You can use this as a starting point: https://jsfiddle.net/doezwsmu/

**Comment by agc93** [comment]
Hmm, in reproducing it, the same behaviour happens if I set `supporting-text` to an empty string for example.

https://jsfiddle.net/3j4okukL/

**Comment by agc93** [comment]
Any luck with this? Any more info I can provide?

**Comment by posva** [comment]
Why do you have an empty string? The `action` prop should not be present if empty, instead, you can handle that case in the event listener.
Other props are more of an issue to me. Can you show me your use case, please?

**Comment by agc93** [comment]
I am wrapping the `mdl-card` up in a custom component with it's own prop for a link, which is not a required prop. Something like:
```
export default {
	props: {
		target: {
			type: string,
			required: false
		}
	},
	computed: {
		showLinks() {
			return target != null;
		}
	}
}
```

Then in my template, I thought I could do something like:
```
<mdl-card :title="someOtherProp" :actions="showLinks ? 'action' : ''"></mdl-card>
```
but apparently not.

**Comment by agc93** [comment]
Also that fiddle I linked demonstrates the effect with `supporting-text`. If you change `:supporting-text="empty"` to `:supporting-text="title"`, the component shows, change it back to `empty` (an empty string prop), and it breaks again.

**Comment by posva** [comment]
You can actually set the value to `true` to make it pass. It's so unintuitive...
Changing it to `false` would make more sense. I'll check what was blocking me from doing so.

**Comment by posva** [comment]
Checking for `el` in the if should do it

**Comment by posva** [comment]
Couldn't find the time to do this. Doing it tomorrow alongside #56

**Comment by agc93** [comment]
Awesome! Thanks for being so quick!

Was this picked up in the 0.9.3 release?

**Comment by posva** [comment]
It's not that fast, but thank you.
It is, indeed on the last release. You can check the notes on each release to see what have been included 😉
