### ISSUE TITLE
Support for Vue 2

### ISSUE THREAD

**Issue by htc550605125** [posva/vue-mdl#61]
I'm using vue 2.0.0 rc4 with webpack. I tried the example in the README.MD but it failed, here is the output of the console

```
vue.js?3de6:2508[Vue warn]: failed to compile template:

<label v-bind:for.once="id" v-bind:class="{ &quot;is-disabled&quot;: disabled, &quot;is-checked&quot;: isChecked }" class="mdl-checkbox mdl-js-checkbox"><input v-bind:value="value" type="checkbox" v-bind:id.once="id" v-model="checked" v-bind:disabled="disabled" class="mdl-checkbox__input"/><span class="mdl-checkbox__label"><slot></slot></span></label>

- invalid expression: v-bind:class="{ &quot;is-disabled&quot;: disabled, &quot;is-checked&quot;: isChecked }"

 (found in component <MdlCheckbox>)
```

What's wrong with the quotes ?

**Comment by posva** [comment]
ATM vue-mdl only supports Vue 1
@petejohanson Is actually working on the migration for Vue 2. I'm confident about having a working release for Vue 2 by the end of this week

**Comment by htc550605125** [comment]
Thanks! Looking forward for your updates :)

**Comment by posva** [comment]
@htc550605125 At the end I couldn't find enough time to work on this. I'll try again this week

**Comment by pksunkara** [comment]
I am looking forward to this too 😄

**Comment by posva** [comment]
It's almost finished for an alpha but I need to update the docs first. I'll do my best to find the time for this.

**Comment by delueg** [comment]
+1

**Comment by weepy** [comment]
how close is this ? keen to use for a new vue 2.0 project x

**Comment by posva** [comment]
Very close. I'm rewriting the docs. The progress can be seen on https://github.com/posva/vue-mdl/tree/ftr_vue_two
Some components are still misbehaving.
After this, I'll focus on an mdl 2 version

**Comment by mimani** [comment]
+1, waiting to use it in the project I have started.

**Comment by posva** [comment]
Glad to hear more people want it!
You can expect a prerelease version on Monday
The release will come once I make the project Vue 1 and 2 compatible. After that, I'll start working on integrating mdl 2. This time for Vue 2 only

**Comment by node-gita** [comment]
+1 waiting for this, Thanks.

**Comment by yoyo930021** [comment]
+1 waiting for this.
Thank you!

**Comment by posva** [comment]
I added an alpha and published it under the `next` npm tag
I may have forgotten some breaking change details:
https://github.com/posva/vue-mdl/releases/tag/v1.0.0-alpha.1

Feedback is welcome!

**Comment by mimani** [comment]
Thanks for pushing it. I tried it, however I am not able to get this working:

Here is my package.json:

    ...
    "serve-favicon": "^2.3.0",
    "vue": "^2.0.0",
    "vue-mdl": "^1.0.0-alpha.1",
    "vue-router": "^2.0.0",
    "vue-server-renderer": "^2.0.0",
    "vuex": "^2.0.0",
    "vuex-router-sync": "^3.0.0"
    ....

I am using `webpack`, I added following in my `app.js`: 

    import VueMdl from 'vue-mdl'
    Vue.use(VueMdl)

Only doing this, I start getting

>Internal Error 500

and in terminal

>error during render : /

Do I have to do something different to make this work?

**Comment by smolinari** [comment]
@posva Hey Eduardo,

I've noticed, in a way, some double work being done between you and the developer who created [Quasar-Framework](http://quasar-framework.org/). I know it's fun to do your own thing and get accolades for it, which you deserve for sure, but Razvan has something going with his framework (which has both mdl and ios themes). Razvan also just migrated Quasar to Vue 2 also. 

I am not sure if this is a good suggestion or not, or if it might insult you (which isn't my intention) but you could join Razvan to help work on Quasar. Sort of "join forces" with him. I think then the doubled up work would be saved and Quasar could really take off.  

It's just an idea. :smile: 

Scott

**Comment by posva** [comment]
@mimani That seem to be a problem with SSR. You must have some stack trace somewhere with more information.

@smolinari hey Scott. I checked quasar code source and there is no mdl there. He's just developing a custom Material theme there so there's, unfortunately, nothing in common. Thanks for the suggestion though

**Comment by smolinari** [comment]
Yes, mdl itself isn't being used, but the "making reusable components" goal is definitely the same between you both. Maybe you could introduce mdl into Quasar as a "proper" material theme? :smile: 

Scott

**Comment by posva** [comment]
@smolinari I wouldn't recommend that as the current state of MDL 😬 . It's not flexible enough to be integrated into a framework, hopefully, mdl 2 can change that. However Quassar must be reusing logic between components and adapt them to both, ios and md themes. I fear in the end it would be harder to maintain a reusable version for quassar

**Comment by smolinari** [comment]
@posva - You'd have to ask Razvan about how he is getting the theme stuff done. I am as of yet, a total noob to Quasar. I just noticed you guys seemed to be heading in similar directions and thought you could both do better and save time and effort joining forces. 

Scott

**Comment by posva** [comment]
Thanks for pointing it out but as I said I don't think it'll be beneficial for quasar because of the current lack of flexibility with mdl

**Comment by vanderlin** [comment]
lifecycle hooks, `ready` has been deprecated. https://github.com/vuejs/vue/issues/2873 use `mounted`.

**Comment by paulogdm** [comment]
+1!!!

**Comment by dsl101** [comment]
Any news on v-mdl textfields? It seems the `.sync` modifier is now deprecated. What's the best approach for `<mdl-textfield>` now?

**Comment by posva** [comment]
@dsl101 The use of broadcast was an error on my part.
Docs are not finished yet, but you can help if you want. The v2 is on the `next` branch.

**Comment by dsl101** [comment]
Yes, I gathered the docs are for the old version. When I install vue-mdl@next I get vue-mdl@1.0.0-alpha.2 - is that right?

I would love to help, but I'm not sure how _much_ help I can be at this stage - I'm new to Vue as well as vue-mdl... But building an app with everything so starting to see how it hangs together.

**Comment by posva** [comment]
@dsl101 yes, it should also be printed by npm or yarn.
I didn't make things easy for others to contribute in v1 but that won't be the case for v2 because I've learned a lot during this last year to make this a better open source project. However, you don't need much to help migrate the docs, except for some guidance I've not posted anywhere 😅 
Migrating docs is basically renaming files from `doc/src/partial` to `doc/src/views`. You can inspire from this commit: https://github.com/posva/vue-mdl/commit/293c0ab862f24a0aa19de8d4d7ce2a6ba8750926
I've been also moving things from jade/pug to html but you don't need to. Some props have changed, in that case, you have to check the component in the src folder. Don't worry if you don't manage to do it. I haven't added any migration guide for contributors because I thought I'd be able to migrate it faster

**Comment by posva** [comment]
Done with latest tag

**Comment by michaelalhilly** [comment]
I'm still experiencing this issue with disabled.
