### ISSUE TITLE
dialogs does not stop tabbing on the background

### ISSUE THREAD

**Issue by freeflyhm** [posva/vue-mdl#63]
This can be reproduced on the sample page on http://posva.net/vue-mdl/#!/dialogs

in the Dialog section click the button to show Dialog
keep hitting tab key

result: tab going through background page and data can also be entered.

Hope someone can advise on this problem. Thanks.

**Comment by posva** [comment]
It's possible to override the dialog behaviour to keep iterating inside the the dialog

**Comment by posva** [comment]
I'll use [tabbable](https://github.com/davidtheclark/tabbable) or [focus-trap](https://github.com/davidtheclark/focus-trap) to keep the tab behaviour inside the dialog

**Comment by posva** [comment]
@freeflyhm I added this at v1.0.0-alpha.2
I'll add it to 0.x too
