### ISSUE TITLE
Autocomplete label doesn't clear with dynamic data

### ISSUE THREAD

**Issue by kyoukhana** [posva/vue-mdl#65]
For some reason Autocomplete label doesn't clear with dynamic data.

**Comment by posva** [comment]
@kyoukhana Can you be more specific, please. Where is this happening and how does it happen. Can you create a repro from this: https://jsfiddle.net/posva/2hr9z7xk/

**Comment by posva** [comment]
@kyoukhana Any news?

**Comment by kyoukhana** [comment]
Sorry for the delay.  I just setup a Git Repo for this issue take a look. 

[](https://github.com/kyoukhana/mdl-label)

Please let me know if you have any questions.

**Comment by posva** [comment]
@kyoukhana Please, set up a minimal repro with the jsfiddle I provided you. It's easier for me to check and help you...

**Comment by kyoukhana** [comment]
The problem is that with JSFiddle you can't use Lazy Load Routing.  This github repo basically isolates the issue.

**Comment by posva** [comment]
You don't need lazy loading to reproduce an issue with vue-mdl

**Comment by kyoukhana** [comment]
Finally i put together a fiddle.  If you load the fiddle you will see that the label is still there when user data is loaded

https://jsfiddle.net/kyoukhana/jv061bL4/19/

Thanks for the help.  This is using vue router.

**Comment by posva** [comment]
You were not using VueMdl
Here's the fixed version: https://jsfiddle.net/posva/rwc40m4x/
You should read the docs 😄 
http://posva.net/vue-mdl/#!/usage
