### ISSUE TITLE
Select inside dialog change dialog size

### ISSUE THREAD

**Issue by karlpatrickespiritu** [posva/vue-mdl#66]
When I try to change the selection option inside a dialog, the dialog body resizes.

![2](https://cloud.githubusercontent.com/assets/10472504/19071739/3420cb90-8a64-11e6-93b2-6d8cb8e1e400.png)

![1](https://cloud.githubusercontent.com/assets/10472504/19071748/3a7f4b4c-8a64-11e6-8d8a-d2c8ca57d845.png)

**Comment by posva** [comment]
I'm sorry, I cannot see the difference. Can you provide a repro using this as a starting point? https://jsfiddle.net/posva/2hr9z7xk/

**Comment by karlpatrickespiritu** [comment]
Seems this only occurs when placing the dialog inside a card. Placed my dialog outside and works like a charm. Anyway, thanks. Closing this issue.

**Comment by posva** [comment]
Oh, I see, you can use `v-transfer-dom` like in the docs http://posva.net/vue-mdl/#!/dialogs

**Comment by karlpatrickespiritu** [comment]
Yep, I missed that one. Thanks @posva! Great work.
