### ISSUE TITLE
Snackbar (mdl 1.1)

### ISSUE THREAD

**Issue by martinlindhe** [posva/vue-mdl#7]
Snackbar is a new mdl feature; documented here: https://getmdl.io/components/index.html#snackbar-section

Here is a rough impl of a vue component for the mdl-snackbar, that can be used as a basis for this feature: https://gist.github.com/martinlindhe/8be3cbe036d5582eba15

**Comment by posva** [comment]
:smile: Thanks for the hint. I saw the snackbar and the dialog #6 in mdl 1.1
I'm definetely getting onto those soon. I'll have to create a contributing.md doc as well as a roadmap so people can follow the progress. It's kinda hard to work alone on this
