### ISSUE TITLE
Document that v-mdl-ripple-effect is removed

### ISSUE THREAD

**Issue by vanderlin** [posva/vue-mdl#71]
when adding `v-mdl-ripple-effect` to a button I am getting this error. Not sure why? I am working with Vue 2.0.

```
app.js?5dee:20 TypeError: Cannot read property 'el' of undefined(…)
```

`<mdl-button v-mdl-ripple-effect>Ripple Effect</mdl-button>`

**Comment by posva** [comment]
The v-mdl-ripple effect was deprecated on 0.x. It hasn't been removed yet but it's not supported anymore. Use the class alternative instead `mdl-js-ripple-effect`. I have to make it clearer on the docs 😛

**Comment by posva** [comment]
In the meantime, I added a note on the release notes

**Comment by posva** [comment]
It's now removed!
