### ISSUE TITLE
Adding click handlers to menu items

### ISSUE THREAD

**Issue by dsl101** [posva/vue-mdl#74]
I'm converting a plain Vue / MDL project to use vue-mdl and hit this snag. Original code for a menu:

    <button id="projectMenu" class="mdl-button mdl-js-button mdl-button--icon">
      <i class="material-icons">more_vert</i>
    </button>
    <ul class="mdl-menu mdl-menu--bottom-left mdl-js-menu mdl-js-ripple-effect" for="projectMenu">
      <li class="mdl-menu__item" v-for="project in otherProjects" :key="project" @click="changeProject">{{project}}</li>
    </ul>

replaced with this:

    <mdl-button id="projectMenu" icon="more_vert"></mdl-button>
    <mdl-menu for="projectMenu">
      <mdl-menu-item v-for="project in otherProjects" :key="project" @click="changeProject">{{project}}</mdl-menu-item>
    </mdl-menu>

I tried `v-on:click` instead of the shorthand `@click` but still no event is fired. Is there a different way to attache event handlers to menu items in vue-mdl?

**Comment by dsl101** [comment]
Hmm. Same thing happening with buttons. So, I'm hoping it's not attaching handlers that's the problem, but my setup.

I'm using Vue 2 and Webpack, installed via vue-cli. I then installed MDL and vue-mdl via npm, and the versions are:

    $ npm list | grep vue
	├── vue@2.1.0
	├─┬ vue-loader@9.9.5
	│ ├── vue-hot-reload-api@2.0.6
	│ ├─┬ vue-template-compiler@2.1.0
	│ └── vue-template-es2015-compiler@1.2.4
	├─┬ vue-mdl@1.0.0-alpha.2
	├── vue-style-loader@1.0.0

index.html includes MDL via the CDN:

    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.2.1/material.blue_grey-orange.min.css">
    <script src="https://code.getmdl.io/1.2.1/material.min.js"></script>

Anything obviously wrong with what I'm doing that would lead to `@click` failing? Nothing is output to console, so not sure what else I can look at...

Many thanks for any help.

**Comment by posva** [comment]
you're just missing the `native` modifier

**Comment by dsl101** [comment]
Tx - not had to use that before. Still learning Vue... :).

**Comment by eric-burel** [comment]
The doc is not very clear about modifiers, and using `native` seems unnatural to me.

In React (yes I am that one annoying guy that comes from React and uses Vue from time to time and always misses React features) we would simply pass down all props to the button, including event bindings: `const myNiceButton = ({myUsefulProps, ...otherProps) => (<div><button {...otherProps}></button></div>)`.
This way `myNiceButton` behaves as an enhanced HTML button, and `<myNiceButton onClick="foobar"/>` intuitively works.

Is this doable with Vue ?

Some relevant issue: [https://github.com/vuejs/vue/issues/6003]()
