### ISSUE TITLE
Enhancement: Add a focus() (and blur()?) method to mdl-textfield

### ISSUE THREAD

**Issue by dsl101** [posva/vue-mdl#79]
I'm currently battling to make a login form using 2 mdl-textfields and an mdl-button. I'd like the Enter key to move focus to the next text box (e.g. Username to Password), and then from Password to fire the Login button. Getting the `keyup` events is no problem (`@keyup.native="onKeyUp"`), but setting focus without resorting to id's and `document.getElementById()` is proving tricky. I tried the Vue `ref="password"` and then using `this.$refs.password.$el.focus()`, but of course that targets the div which is the parent of the input field, which then ignores the focus request. Or, am I going about this wrong?

If there's another vmdl component which already does something similar, perhaps now would be a good time to try a pull request. Can you point me at one which does something like this I could look at?

**Comment by posva** [comment]
Proxying focus and blur methods is definitely legit. If you want to do the PR, you have to add 2 methods to the textfield component and inside the component focus the textarea or the input. This can be done with a simple `this.$el.getElementsByTagName('input')` and also for textarea or with a ref. I'm not sure if the same ref name would work but you can try, it's definitely better if it's possible.

**Comment by dsl101** [comment]
Just a note to say I'm working on this, but waiting on #82 before I can test code changes.

**Comment by dsl101** [comment]
I added these methods, which seem to have the desired effect. In `v-if` / `v-else-if` sections which generate the actual `<input>` tag, it appears you can reuse the 'ref', so providing you only end up with one `focusTarget` ref, all is well:

    methods: {
      focus () {
        this.$refs.focusTarget.focus()
      },
      focusAndSelect () {
        this.$refs.focusTarget.focus()
        this.$refs.focusTarget.select()
      },
      blur () {
        this.$refs.focusTarget.blur()
      }
    },

**Comment by dsl101** [comment]
Now the branch issue is solved, I've created #85 for the focus stuff.

**Comment by posva** [comment]
@dsl101 Cool, thanks!
