### ISSUE TITLE
mdl-menu no longer compiles in template

### ISSUE THREAD

**Issue by dsl101** [posva/vue-mdl#83]
Not sure exactly what triggered this, but I was getting an error in the template traced back to mdl-menu. It seems it objects to the use of the reserved JavaScript word 'for' in the properties now - something new in vue@2.1.4?

	[Vue warn]: failed to compile template:
	<ul v-bind:for.once="for" class="mdl-menu mdl-js-menu"><slot></slot></ul>
	- avoid using JavaScript keyword as property name: "for" in expression v-bind:for.once="for"
	(found in component <MdlMenu>)

Anyway, changing menu.vue to this:

	<template lang="jade">
	ul.mdl-menu.mdl-js-menu(v-bind:for.once='menufor')
	  slot
	</template>

	<script>
	export default {
	  props: ['menufor'],
	  ready () {
	    componentHandler.upgradeElement(this.$el, 'MaterialMenu')
	  }
	  // beforeDestroy () {
	    // TODO Remove mdl event listeners added. This was previously
	    // this.$el.MaterialMenu.mdlDowngrade()
	    // But has been removed on 1.1
	}
	</script>

and then in use:

    <mdl-menu menufor="projectMenu">

seems to solve the problem. But I can't test further yet due to the other issue I posted about `mdl-textfield`, as the app I'm building is broken until I can fix that :(

I also don't really like having to use a different word here - perhaps there's a way to tell Vue to be more tolerant in this scenario?

**Comment by posva** [comment]
Thanks for reporting it!
I need to check a bit further. I'll still like to keep the `for` prop and use a computed for the template

**Comment by dsl101** [comment]
In the mean time, I changed it to use `trigger` instead, which I think still reads reasonably well in the template code:

    <mdl-button id="account" icon="account_circle"></mdl-button>
    <mdl-menu trigger="account">
      <mdl-menu-item @click.native="changePassword">Change Password</mdl-menu-item>
      <mdl-menu-item @click.native="logout">Logout</mdl-menu-item>
    </mdl-menu>

It works for me in that the button with id 'account' is the 'trigger' for opening the menu.

**Comment by posva** [comment]
Closing since this was using an outdated version
