### ISSUE TITLE
mdl-textfield floating label no longer works (with solution)

### ISSUE THREAD

**Issue by dsl101** [posva/vue-mdl#84]
I think this is because the lifecycle hooks have changed and `ready()` is now `mounted()`. I also had to move the `label` property to be a data element to avoid the warning about mutating properties. Since I'm only using `floatingLabel`, I suspect there is more that would need to be done to properly implement `label` now though, since it's not a real property any more.

**Comment by posva** [comment]
0.x is not compatible with Vue 2. Use the v1 (alpha) for that.
Now that I think of it, if you were using 0.x, please check that the other issues you opened are not occurring with v1 😆 
To install v1 use the `next` tag: `npm i -S vue-mdl@next`

**Comment by dsl101** [comment]
I'm not using 0.x and have installed @next.

**Comment by posva** [comment]
Make sure you have it because it shouldn't be giving you a warning about mutating properties
If you're checking the code on the repo, you should check the v1 branch. Here's the textfield: https://github.com/posva/vue-mdl/blob/v1/src/textfield.vue

**Comment by dsl101** [comment]
You're right of course. I'd been working in the 'develop' branch, which I thought was the latest code... Should have checked. And I also misunderstood some details about switching between the registry installed version (which _is_ @next), and my local build of v-mdl in my app. I will update everything later and recheck.

Many thanks for your patience :)

**Comment by posva** [comment]
Glad I could help 👍
