### ISSUE TITLE
mdl-slider prop check errors

### ISSUE THREAD

**Issue by dsl101** [posva/vue-mdl#87]
First of all, I'm 99% certain I'm using v1 :). Perhaps it's just the docs are out of step, but this:

    <mdl-slider v-on:input="(v) => {this.timeout = v}" :value="timeout" min="0" max="10000" step="500"></mdl-slider>

results in 3 warnings in the console:

	[Vue warn]: Invalid prop: type check failed for prop "step". Expected Number, got String. 
	(found in component <MdlSlider> at /vue/vue-mdl/src/slider.vue)
	[Vue warn]: Invalid prop: type check failed for prop "min". Expected Number, got String. 
	(found in component <MdlSlider> at /vue/vue-mdl/src/slider.vue)
	[Vue warn]: Invalid prop: type check failed for prop "max". Expected Number, got String. 
	(found in component <MdlSlider> at /vue/vue-mdl/src/slider.vue)

and they are repeated every time the slider is updated. Is this in need of an upgrade, or should it be working? If the former, and if it's easier to describe than do, I'm happy to have a go...

**Comment by posva** [comment]
It's actually very simple to fix 😄 
The type should be `[Number, String]` and use a computed property like `stepNumber` to get a Number out of it and use it in every computation
https://github.com/posva/vue-mdl/blob/v1/src/slider.vue#L45

**Comment by dsl101** [comment]
OK - I will do that and create a PR

**Comment by dsl101** [comment]
And, when working with firebase, it's quite convenient to pass `value` as a string too, as that's what they come back from firebase as. Would it be OK to handle `value` in the same way?

**Comment by posva** [comment]
@dsl101 I don't understand what you mean, you can have numbers in firebase

**Comment by dsl101** [comment]
Yes, but in practice, especially if you use JSON import / export, many times things end up as strings, and it's quite tedious to work through the database converting them. I guess it should really have more validation, but none of my data is user-provided, so letting the slider handle strings and use `parseInt()` there seemed reasonable - as for the min / max / step values.

**Comment by posva** [comment]
Actually JSON can have numbers too

**Comment by dsl101** [comment]
Indeed. Then I have no idea what converted _some_ of my numbers in to strings. But there they are - must have been cosmic rays. In any case, I'm pleased mdl-slider is more tolerant of me now :)
