### ISSUE TITLE
Getting mdl-radio to work

### ISSUE THREAD

**Issue by dsl101** [posva/vue-mdl#89]
I know the docs are a bit behind the code, but would you be able to help me untangle v1 mdl-slider? So far this:

    <mdl-radio @input="toggle" :val="sortOrder" value="sortAscending">Ascending Order</mdl-radio>
    <mdl-radio @input="toggle" :val="sortOrder" value="sortDescending">Descending Order</mdl-radio>

just doesn't work. I've got a local data property called `sortOrder`, and it is initialised to "sortAscending", and the `toggle()` function assigns what it receives from the emited `input` event. But it ends up stuck with both radio buttons selected, and no change to the `sortOrder` value.

**Comment by dsl101** [comment]
OK - so _this_ works better. Set `name` and switch round `val` and `value`. Perhaps there's another name for one of those to make it more intuitive?

        <mdl-radio name="sort" @input="toggle" val="sortAscending" :value="sortOrder">Ascending Order</mdl-radio>
        <mdl-radio name="sort" @input="toggle" val="sortDescending" :value="sortOrder">Descending Order</mdl-radio>

**Comment by posva** [comment]
The value is used for the v-model. val is the value attribute on the input.
Here's an example: https://github.com/posva/vue-mdl/blob/v1/test/components/Radio.vue

**Comment by dsl101** [comment]
I think that's the essence of my confusion - "value is for v-model, val is for value"

**Comment by posva** [comment]
Yeah, it's really confusing 😓
