### ISSUE TITLE
[Vue warn]: v-model does not support element type: DIV

### ISSUE THREAD

**Issue by dacodekid** [posva/vue-mdl#9]
Getting this `warning` for `mdl-textfield` (haven't tried other components though) and noticed there is an extra `div` element wraps the `textbox` & `label`.  Not sure, this is what causing the waring / I'm using the library correctly or not (couldn't find any doc/example with `v-model` usage).  

This generates the warning
```html
    <mdl-textfield  floating-label="Status"
                    :value.sync="status.name"
                    v-model="status.name"
                    v-on:keyup.enter="addStatus">
    </mdl-textfield>
```

Using plain `mdl` doesn't produce this warning. 
```html
    <div class="mdl-textfield mdl-js-textfield  mdl-textfield--floating-label">
      <input  type="text" value=""
              id="statusTextBox"
              class="mdl-textfield__input"
              v-model="status.name"
              @keyup.enter="addStatus">
      <label class="mdl-textfield__label" for="statusTextBox">Enter a Status</label>
    </div>
```

![screen shot 2016-02-08 at 8 48 17 pm](https://cloud.githubusercontent.com/assets/10047844/12905552/08d85496-cea6-11e5-916d-226cbbd0f0d6.png)

**Comment by posva** [comment]
Hi, thanks for the issue.
`v-model` should not be used with `mdl-textfield` as the `:value.sync` is there for that purpose. However I'm not sure about events as they're attached to the div that contains the textfield. I'm going to include that on the documentation as it doesn't seem to be clear (You can also open a PR if you want, that would make me happy :smile: )

I just found there's an extra div that seems to have some meaning when the expandable prop is used but I'll give it a look asap

**Comment by dacodekid** [comment]
@posva :

1. Removing `v-model` fixes the waring :+1: .  Sorry but I tried many things at once and had an impression that I had to use both `sync & v-model`.

2. I wouldn't mind participating (or open a PR) but I had spent only an hr or so with `vue-mdl` + [this issue here](https://github.com/posva/vue-mdl/issues/10)
