### ISSUE TITLE
Dialogs, option to disable focus-trap

### ISSUE THREAD

**Issue by dabroder** [posva/vue-mdl#92]
Hello Eduardo, a property to disable `focus-trap` in MdlDialog would be useful in many cases.
I'm having trouble with `md-date-time-picker` that render outside MdlDialog.

Great Job! Greetings from Argentina.

**Comment by posva** [comment]
Indeed, I should add a `no-focus-trap` prop to the dialog. A PR is welcome as well, it's quite simple actually
