### ISSUE TITLE
Uncaught ReferenceError: _h is not defined in render	@ vue-mdl.js

### ISSUE THREAD

**Issue by rvramesh** [posva/vue-mdl#94]
Hi I am trying out vue-mdl 1.0.0alpha.2 on a project scaffolded by vue-cli. When I am trying to place a simple button I am getting the "Uncaught ReferenceError: _h is not defined" error. I am attaching the screen shot for reference. 
![screen shot 2016-12-17 at 10 56 26 pm](https://cloud.githubusercontent.com/assets/366183/21288564/bb5186fe-c4ac-11e6-9750-90f3ff538e35.png)

I have placed the code which is causing this @ https://github.com/rvramesh/my-project

Can you please let me know if I am doing any mistake.

As per my analysis the _h method reference in https://github.com/posva/vue-mdl/blob/develop/dist/vue-mdl.js is not available. But I am not able to figure out where I am going wrong.

**Comment by posva** [comment]
It was an issue that needed me to rebuild vue-mdl. I rebuilt and released (some) new alphas. Update to the last version and you'll be good. Thanks for telling me 👍

**Comment by rvramesh** [comment]
Thanks! This is resolved in alpha5 which I tested.
